import {
  backend,
  bootstrap,
  creator,
  css,
  docker,
  drone,
  equiz,
  fasi,
  figma,
  gas,
  git,
  html,
  javascript,
  kkg,
  mobile,
  mongodb,
  nodejs,
  pinia,
  postgres,
  quran,
  reactjs,
  redux,
  remotepilot,
  rpi,
  sampan,
  sawit,
  school,
  tailwind,
  threejs,
  typescript,
  vue,
  web,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Web Developer",
    icon: web,
  },
  {
    title: "React Native Developer",
    icon: mobile,
  },
  {
    title: "Backend Developer",
    icon: backend,
  },
  {
    title: "Content Creator",
    icon: creator,
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "Vue JS",
    icon: vue,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Pinia",
    icon: pinia,
  },
  {
    name: "Bootstrap",
    icon: bootstrap,
  },
  {
    name: "postgreSQL",
    icon: postgres,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "MongoDB",
    icon: mongodb,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  {
    name: "docker",
    icon: docker,
  },
];

const experiences = [
  {
    title: "Drone Instructor (Part Time)",
    company_name: "Indonesian Aerosport Federation",
    icon: fasi,
    iconBg: "#fff",
    date: "August 2019 - Now",
    points: [
      "Developed comprehensive curricula for drone pilot certification programs, covering aviation regulations, airspace restrictions, emergency procedures, and ethical considerations.",
      "Taught drone pilots in flight control, navigation, and drone system operations to ensure safe and effective drone operation.",
      "Created engaging and informative training materials on drone technology, flight planning, weather conditions, and risk management for effective pilot education.",
    ],
  },
  {
    title: "Chief Executive Officer",
    company_name: "PT. Remote Pilot Indonesia",
    icon: rpi,
    iconBg: "#fff",
    date: "June 2021 – December 2022",
    points: [
      "Provided drone-based training and mapping services, delivering comprehensive instruction and accurate mapping solutions.",
      "Designed and executed marketing strategies to attract a wide range of clients, resulting in successful collaborations with ministries, state-owned enterprises, and private companies.",
      "Creating a website-based social media platform for remote pilots across Indonesia.",
    ],
  },
  {
    title: "Director and Drone Instructor",
    company_name: "CV. Galeri Angkasa Sejahtera",
    icon: gas,
    iconBg: "#fff",
    date: "June 2018 – December 2021",
    points: [
      "Provided drone-based training and mapping services.",
      "Delivered over 200 drone training sessions throughout Indonesia, providing comprehensive instruction and hands-on experience.",
      "Designed and executed marketing strategies to attract a wide range of clients, resulting in successful collaborations with ministries, state-owned enterprises, and private companies.",
    ],
  },
  {
    title: "UAV and GIS Officer",
    company_name: "Keling Kumang Group",
    icon: kkg,
    iconBg: "#fff",
    date: "December 2016 – December 2017",
    points: [
      "Provided maps generated by drones, offering accurate and up-to-date visual representations of various areas for diverse applications.",
      "Created over 4,000 palm oil plantation maps in Sintang and Sekadau regencies, providing detailed information for efficient management and decision-making.",
      "Created work plans and delivered implementation reports, evaluating project effectiveness and success.",
    ],
  },
  {
    title: "Head of IT and UAV Program Officer",
    company_name: "Perkumpulan Sampan Kalimantan",
    icon: sampan,
    iconBg: "#fff",
    date: "March 2013 – September 2016",
    points: [
      "Developed social media campaign strategies to engage target audiences effectively, involving defining objectives, creating compelling content, and analyzing performance for improvement.",
      "Collected aerial map data, photos, and videos using drones for data acquisition purposes.",
      "Managed all institutional social media channels, overseeing content creation, engagement, and audience growth strategies.",
    ],
  },
  {
    title: "Honorary Teacher",
    company_name: "Junior High School 05 Satap Belimbing",
    icon: school,
    iconBg: "#fff",
    date: "August 2011 – March 2013",
    points: [
      "Taught Information Technology and Communication lessons, covering topics such as computer skills, digital literacy, communication tools, and online safety.",
      "Guided and mentored Scout organization, fostering character development, outdoor skills, teamwork, and leadership through engaging activities and camp experiences.",
      "Designed comprehensive learning plans, outlining objectives, content, instructional strategies, and assessment methods, to facilitate effective and structured learning experiences for students.",
    ],
  },
  {
    title: "Surveyor Officer",
    company_name: "CV Ilham Ahmad Kurnia",
    icon: sawit,
    iconBg: "#fff",
    date: "January 2011 – May 2011",
    points: [
      "Negotiated land purchases with residents on behalf of the company, ensuring fair and mutually beneficial agreements while addressing concerns and maintaining positive relationships.",
      "Evaluated the achievements of coconut plantation land purchases, assessing factors such as the number of acquired plots, the total area obtained, adherence to budgetary constraints, and the overall success of the land acquisition process.",
      "Measured the land area being transferred and calculated the costs associated with the land acquisition, considering factors such as size, location, and any additional expenses involved.",
    ],
  },
];

const projects = [
  {
    name: "Drone Indonesia",
    description:
      "A social media platform for Indonesia's drone community. Connect, share, and collaborate with fellow enthusiasts, professionals, and hobbyists!.",
    tags: [
      {
        name: "PHP",
        color: "blue-text-gradient",
      },
      {
        name: "MySQL",
        color: "green-text-gradient",
      },
      {
        name: "Bootstrap",
        color: "orange-text-gradient",
      },
    ],
    image: drone,
    source_code_link: "https://drone.or.id/",
  },
  {
    name: "Remote Pilot Indonesia",
    description:
      "An application to showcase portfolios for remote pilots, complete with their skills and a list of certifications they possess.",
    tags: [
      {
        name: "PHP",
        color: "blue-text-gradient",
      },
      {
        name: "MySQL",
        color: "green-text-gradient",
      },
      {
        name: "Bootstrap",
        color: "orange-text-gradient",
      },
    ],
    image: remotepilot,
    source_code_link: "https://remotepilot.id/",
  },
  {
    name: "Qur'an App",
    description:
      "A web based application quran.An all-in-one Quran app with standard features, including daily prayer times, and a collection of daily supplications. A comprehensive spiritual companion.",
    tags: [
      {
        name: "Rest API.js",
        color: "blue-text-gradient",
      },
      {
        name: "Vue.Js",
        color: "green-text-gradient",
      },
      {
        name: "tailwind.css",
        color: "pink-text-gradient",
      },
      {
        name: "axios.js",
        color: "pink-text-gradient",
      },
    ],
    image: quran,
    source_code_link: "https://quran.liupurnomo.com/",
  },
  {
    name: "Equiz Plus",
    description:
      "A web based online test platform with integration of Text-to-Speech and Speech-to-Text accessibility.",
    tags: [
      {
        name: "Express.js",
        color: "blue-text-gradient",
      },
      {
        name: "Postgres",
        color: "green-text-gradient",
      },
      {
        name: "Sequelize",
        color: "orange-text-gradient",
      },
      {
        name: "JasonWebToken",
        color: "blue-text-gradient",
      },
      {
        name: "Bcrypt",
        color: "yellow-text-gradient",
      },
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "bootstrap",
        color: "pink-text-gradient",
      },
    ],
    image: equiz,
    source_code_link: "https://e-quiz.xyz/",
  },
];

export { experiences, projects, services, technologies };
