import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../public/styles/tailwind.css";
import { Footer } from "./layout/footer";
import Header from "./layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
